//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<footprint> footprint { get; set; }
        public virtual DbSet<note> note { get; set; }
        public virtual DbSet<pictravel> pictravel { get; set; }
        public virtual DbSet<province> province { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<viewspot> viewspot { get; set; }
    }
}
